{
 "title": "Zero-Downtime Deployment",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "전체 처리량 (Total TPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\nrate(http_server_requests_seconds_count{job=\"fitU-app\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "평균 응답 시간 (Average Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[1m]))\n/\nsum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "인스턴스별 처리량 (Instance TPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instance) (\nrate(http_server_requests_seconds_count{job=\"fitU-app\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 상태 코드 분포",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (\nrate(http_server_requests_seconds_count{job=\"fitU-app\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 응답 시간 (95th Percentile Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n\tsum(rate(http_server_requests_seconds_bucket{job=\"fitU-app\"}[1m])) \n\tby (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}